
DROP SEQUENCE  "LAB3_DEPARTMENTS_SEQ";
DROP SEQUENCE  "LAB3_EMPLOYEES_SEQ";
DROP TABLE  "LAB3_EMPLOYEES" cascade constraints;
DROP TABLE  "LAB3_DEPARTMENTS" cascade constraints;


   CREATE SEQUENCE   "LAB3_DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE   "LAB3_EMPLOYEES_SEQ"    MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Table LAB3_DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE  "LAB3_DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER(*,0), 
	"DEPARTMENT_NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DIMA.LAB3_DEPARTMENTS
SET DEFINE OFF;
Insert into DIMA.LAB3_DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,DESCRIPTION) values ('1','SALES',null);
Insert into DIMA.LAB3_DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,DESCRIPTION) values ('2','ACCOUNTING',null);
Insert into DIMA.LAB3_DEPARTMENTS (DEPARTMENT_ID,DEPARTMENT_NAME,DESCRIPTION) values ('3','IT',null);
--------------------------------------------------------
--  DDL for Index LAB3_DEPARTMENTS__NAME
--------------------------------------------------------

  CREATE INDEX  "LAB3_DEPARTMENTS__NAME" ON  "LAB3_DEPARTMENTS" ("DEPARTMENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAB3_DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX  "LAB3_DEPARTMENTS_PK" ON  "LAB3_DEPARTMENTS" ("DEPARTMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LAB3_DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE  "LAB3_DEPARTMENTS" ADD CONSTRAINT "LAB3_DEPARTMENTS_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE  "LAB3_DEPARTMENTS" MODIFY ("DEPARTMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE  "LAB3_DEPARTMENTS" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger LAB3_DEPARTMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER  "LAB3_DEPARTMENTS_TRG" 
before insert on lab3_departments 
for each row 
begin
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DEPARTMENT_ID IS NULL THEN
      SELECT LAB3_DEPARTMENTS_SEQ.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
end;
/
ALTER TRIGGER  "LAB3_DEPARTMENTS_TRG" ENABLE;




--------------------------------------------------------
--  DDL for Table LAB3_EMPLOYEES
--------------------------------------------------------

  CREATE TABLE  "LAB3_EMPLOYEES" 
   (	"EMP_ID" NUMBER(*,0), 
	"EMP_NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENT_ID" NUMBER(*,0), 
	"MANAGER_ID" NUMBER(*,0), 
	"JOB_NAME" VARCHAR2(100 BYTE), 
	"SALARY" NUMBER, 
	"DATE_IN" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."EMP_ID" IS 'id';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."EMP_NAME" IS 'employee  name';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."DEPARTMENT_ID" IS 'department id';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."MANAGER_ID" IS 'manager id';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."JOB_NAME" IS 'job name';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."SALARY" IS 'salary';
   COMMENT ON COLUMN  "LAB3_EMPLOYEES"."DATE_IN" IS 'hire date';
REM INSERTING into DIMA.LAB3_EMPLOYEES
SET DEFINE OFF;
Insert into DIMA.LAB3_EMPLOYEES (EMP_ID,EMP_NAME,DEPARTMENT_ID,MANAGER_ID,JOB_NAME,SALARY,DATE_IN) values ('3','Сидоренко С.С.','2','4','Бухгартер','3333',to_date('18.04.16','DD.MM.RR'));
Insert into DIMA.LAB3_EMPLOYEES (EMP_ID,EMP_NAME,DEPARTMENT_ID,MANAGER_ID,JOB_NAME,SALARY,DATE_IN) values ('1','Иванов И.И.','1',null,'Директор','9999',to_date('01.04.16','DD.MM.RR'));
Insert into DIMA.LAB3_EMPLOYEES (EMP_ID,EMP_NAME,DEPARTMENT_ID,MANAGER_ID,JOB_NAME,SALARY,DATE_IN) values ('2','Петров П.П.','3','1','Программист','5555',to_date('08.04.16','DD.MM.RR'));
Insert into DIMA.LAB3_EMPLOYEES (EMP_ID,EMP_NAME,DEPARTMENT_ID,MANAGER_ID,JOB_NAME,SALARY,DATE_IN) values ('4','Сидоров С.С.','2','1','ГлавБух','4444',to_date('12.04.16','DD.MM.RR'));
--------------------------------------------------------
--  DDL for Index LAB3_EMPLOYEES_PK
--------------------------------------------------------

  CREATE INDEX  "LAB3_EMPLOYEES_PK" ON  "LAB3_EMPLOYEES" ("EMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAB3_EMPLOYEES__NAME_IDX
--------------------------------------------------------

  CREATE INDEX  "LAB3_EMPLOYEES__NAME_IDX" ON  "LAB3_EMPLOYEES" ("EMP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LAB3_EMPLOYEES__MANAGER_IDX
--------------------------------------------------------

  CREATE INDEX  "LAB3_EMPLOYEES__MANAGER_IDX" ON  "LAB3_EMPLOYEES" ("MANAGER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LAB3_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE  "LAB3_EMPLOYEES" ADD CONSTRAINT "LAB3_EMPLOYEES_PK" PRIMARY KEY ("EMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE  "LAB3_EMPLOYEES" MODIFY ("EMP_NAME" NOT NULL ENABLE);
  ALTER TABLE  "LAB3_EMPLOYEES" MODIFY ("EMP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LAB3_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE  "LAB3_EMPLOYEES" ADD CONSTRAINT "LAB3_EMPLOYEES_FK1_MANAGER" FOREIGN KEY ("MANAGER_ID")
	  REFERENCES  "LAB3_EMPLOYEES" ("EMP_ID") ENABLE;
  ALTER TABLE  "LAB3_EMPLOYEES" ADD CONSTRAINT "LAB3_EMPLOYEES_FK2_DEP_ID" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES  "LAB3_DEPARTMENTS" ("DEPARTMENT_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger LAB3_EMPLOYEES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER  "LAB3_EMPLOYEES_TRG" 
before insert on lab3_employees 
for each row 
begin
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.EMP_ID IS NULL THEN
      SELECT LAB3_EMPLOYEES_SEQ.NEXTVAL INTO :NEW.EMP_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
end;
/
ALTER TRIGGER  "LAB3_EMPLOYEES_TRG" ENABLE;

